[tool.poetry]
name = "vip_qml-lstm"
version = "0.1.0"
description = ""
authors = ["TanglyEagle7718"]

[tool.poetry.dependencies]
python = "^3.10"
qiskit = "^1.3.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
